### ISSUE TITLE
Missing Spirtes, do we report here?

### ISSUE THREAD

**Issue by Draevante** [Theawesomeboophis/UndeadPeopleTileset#100]
Are we currently looking out for items without spirites? Happy to aid in reporting this if so.

At a first glance I notice: Training Dummy currently shows a @ symbol. Technology Advertising Brochure showing a semicolon. Aim game target practice kit is a *. Honey dew is ~. Wind vane is >

For mods all the ores in Innawood are without spires.

Anyway I will look for more if that is something you are looking for.

**Comment by Theawesomeboophis** [comment]
These go into the tileset-request channel on the discord, but thank you for reporting. We just fixed mod tilesets and updates are already being worked on.
