### ISSUE TITLE
Heavy Duty Trunk Door is backwards.

### ISSUE THREAD

**Issue by ProjectileWaterfowl** [Theawesomeboophis/UndeadPeopleTileset#12]
The title says it all, really. The handle faces the front of the car, it opens as if raising to the inside, etc. A 180 flip is all that's needed.

![image](https://user-images.githubusercontent.com/8988919/147296310-f4eeddd6-6660-47c4-8713-2c677da2ff0f.png)
![image](https://user-images.githubusercontent.com/8988919/147296333-3f1b3f4e-aef5-47d2-842d-b778e9d77fc1.png)

**Comment by Theawesomeboophis** [comment]
Which spritesheet is this in, it seems like an easy fix.

**Comment by ProjectileWaterfowl** [comment]
Long delay on reply, but should be in vehicles.

**Comment by ProjectileWaterfowl** [comment]
> Which spritesheet is this in, it seems like an easy fix.

normal_vehicle_parts.png

**Comment by Theawesomeboophis** [comment]
Should Be Fixed.
