### ISSUE TITLE
Door rear have incorrect rotation, and opaque door have weird sprites.

### ISSUE THREAD

**Issue by FayFlightee** [Theawesomeboophis/UndeadPeopleTileset#14]
EDITED
So, the normal car door's Rear sprite is clearly incorrectly rotated. Since their "open" sprite is still in the way. Same goes for opaque doors, rear sprite is facing the wrong way.

NOTE: I have Debug Clairvoyance on this screenshot. You cant see through opaque doors normally. But still, the sprite proves itself.
![image](https://user-images.githubusercontent.com/71143790/147716311-2ba54725-650a-4ae5-8525-f6d8938e40e3.png)

**Comment by Theawesomeboophis** [comment]
The sprite is facing the wrong way?

**Comment by FayFlightee** [comment]
> The sprite is facing the wrong way?

Updated the report, sorry for incorrectly saying it last time.
