### ISSUE TITLE
New appliances

### ISSUE THREAD

**Issue by FayFlightee** [Theawesomeboophis/UndeadPeopleTileset#17]
In experimental, some furnitures can now be used as appliances and those appliances version is lacking sprites. We could just copy the texture of the normal one into the appliance version for now.

**Comment by Jan-Blasiak** [comment]
I'm afraid you'll have to make a PR yourself, you're right, it should be quick and easy, but nobody is maintaining this tileset currently.

**Comment by Theawesomeboophis** [comment]
I think a pr to the dda repo is adding looks_like to these if I'm not wrong. If you could send the ids of the items, I can try and assign them sprites, someone is currently helping me fix unpacked so everything should be easier soon. We're currently working on getting the weather sprites from BN working properly.

**Comment by Theawesomeboophis** [comment]
Sorry about updates being slow, I've been trying to finish some of my PRs for dda that have been in the background for a while, weather sprite fix is coming soon tho, I've just been distracted by other things.

**Comment by Jan-Blasiak** [comment]
@Theawesomeboophis don't worry! We're happy there is someone actually picking it up after UDP left!

I genuinely thought the tileset was left to rot, I'm glad I was wrong!

**Comment by Theawesomeboophis** [comment]
No, I'm still figuring out aseprite and how to properly add tiles and stuff, but once I do I'll add more stuff.

**Comment by LyleSY** [comment]
Is this still an issue or has this been fixed in DDA?

**Comment by Theawesomeboophis** [comment]
Most of these have looks_like at this point.
