### ISSUE TITLE
Exodii Quadruped is Bipedal

### ISSUE THREAD

**Issue by Theawesomeboophis** [Theawesomeboophis/UndeadPeopleTileset#2]
Exodii Quadruped is a Bipedal sprite.

**Comment by Theawesomeboophis** [comment]
I made a new sprite for this, and didn't like the way it looked, so I'm redoing it again.

**Comment by TheLyca0n** [comment]
Added the AT-AT style quadruped to my pr, will be included in the merge once I finish off all the feral sprites
