### ISSUE TITLE
Small vacuum oven sprite is invisible.

### ISSUE THREAD

**Issue by lfaga** [Theawesomeboophis/UndeadPeopleTileset#20]
Small vacuum oven sprite is invisible. Just that.

**Comment by Theawesomeboophis** [comment]
Do you have the Id of this item?

**Comment by lfaga** [comment]
vac_oven_small

**Comment by Theawesomeboophis** [comment]
This seems simple enough, I don't know how to do Fgs and Bgs without messing it up tho.
