### ISSUE TITLE
Unpacked version of the tileset

### ISSUE THREAD

**Issue by Firestorm01X2** [Theawesomeboophis/UndeadPeopleTileset#3]
Hello. You may need unpacked version of SDG's tileset.
It it here:
https://github.com/Firestorm01X2/UndeadPeopleUnpacked

I've forked it before SDG deleted it.

**Comment by Firestorm01X2** [comment]
@Theawesomeboophis 
@chaosvolt has experience with tiles as well. If you are going to work with tileset - then it will be good idea to contact him. He can, potentially, help.
You can find him on BN discord server: https://discord.gg/XW7XhXuZ89

**Comment by Theawesomeboophis** [comment]
Thank you for the link.

**Comment by Theawesomeboophis** [comment]
Hey @chaosvolt, I messed up tileconfig.json while trying to add a new sprite, would you mind taking a look at it when you get the chance?
It is here: 
[tile_config.txt](https://github.com/Theawesomeboophis/UndeadPeopleTileset/files/7117651/tile_config.txt)
Thank You in advance.

**Comment by chaosvolt** [comment]
Er, let me see...well, the file being a massive unlinted blob of text is going to make it a giant pain in the ass to find where the error actually is.

In fact yeah, this is going to be impossible to fix because the error message is most likely going to say it's on "line 1" which the entire file content is on.

**Comment by chaosvolt** [comment]
It it at least prints an error message on starting the game it MIGHT be possible to find where the error is, if so can you grab a screenshot?

**Comment by Theawesomeboophis** [comment]
It is throwing errors, hold on, let me ctrl c v real quick.

**Comment by Theawesomeboophis** [comment]
DEBUG    : Error: Json error: <unknown source file>:1:1462707: expecting string but found '{'

rlay_effect_visuals", "bg": 18652}, {"id": "tr_unfinished_construction", "fg": 18653, "rotates": false}, {"id": "vp_basketlg", "fg": 18654, "rotates": false}, {"id": "vp_basketlg_cart", "fg": [18655, 18656, 18657, 18658], "rotates": true}], {
                                                                                                                                                                                                                                                 ^
                                                                                                                                                                                                                                                  "id": "mon_zombie_nemesis", "fg": 18659, "rotates": false}, {"id": "corpse_mon_zombie_nemesis", "fg": 18660, "rotates": false}], "//": "range 18113 to 18672", "sprite_width": 64, "sprite_height": 80, "sprite_offset_x": -16, "sprite_offset_y


 FUNCTION : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 944
 VERSION  : 952d25f
This is causing a loading failure and a crash to main menu.

**Comment by chaosvolt** [comment]
Okay yep, that let me find what seems to be the error.

Ran it through the linter and no syntax problems reported:
[tile_config.txt](https://github.com/Theawesomeboophis/UndeadPeopleTileset/files/7117688/tile_config.txt)

**Comment by Theawesomeboophis** [comment]
Is that the fixed version? If so, that was quick.

**Comment by chaosvolt** [comment]
Yeah, it was just an extraneous `]` injected into the middle of it by accident. Easily checked with: http://dev.narc.ro/cataclysm/format.html

Side note, I hate how whatever editor is used for unpacked tilesets spits out the tile_config output as a giant ugly one-line blob of text.

**Comment by Theawesomeboophis** [comment]
Thank you, I've been trying to fix this for hours and couldn't figure it out.

**Comment by Theawesomeboophis** [comment]
There's another issue occurring, some sprites are appearing as blank white squares.

**Comment by Theawesomeboophis** [comment]
![Relentless Hulk](https://user-images.githubusercontent.com/71793015/132257807-8b875cab-1125-4d3e-a123-39d3f07156c9.png)
What the sprite is supposed to look like
![reality](https://user-images.githubusercontent.com/71793015/132257955-f9a07572-e439-4cf4-924a-0a3db6d64311.png)
What it actually looks like ( couldn't find real hostile indicator in files).

**Comment by Firestorm01X2** [comment]
@Theawesomeboophis  
As far as I understand you need to work with Unpacked version of the tileset. Current repository is final result of packing tileset.

Look at hte ultica: 
https://github.com/I-am-Erk/CDDA-Tilesets/tree/master/gfx/HollowMoon/pngs_large_32x32/monsters/mon_chickenbot
It has separate files. It is unpacked. And it ieven has packing instrucion:
https://i-am-erk.github.io/CDDA-Tilesets/

You need to set up python and few libs. After that just and files and seprate config files and pack using bat sctipts inside https://github.com/Firestorm01X2/UndeadPeopleUnpacked.

I am afraid your current approach will make collective work impossible.

**Comment by Firestorm01X2** [comment]
![screenshot 2021-09-06 002](https://user-images.githubusercontent.com/17512620/132258089-cf8c0e86-620a-4227-a198-e2fd3e228b02.png)

**Comment by Theawesomeboophis** [comment]
How do I set up python?

**Comment by Firestorm01X2** [comment]
Contact us on BN discord server: BN discord server: https://discord.gg/XW7XhXuZ89
There we can start proper planning and work.

**Comment by Firestorm01X2** [comment]
> How do I set up python?

Ultica has doc: https://i-am-erk.github.io/CDDA-Tilesets/
But I can explain it step by step if needed. Just jond BN server.

**Comment by Theawesomeboophis** [comment]
I would rather not join discord, as it is too close to social media.

**Comment by Theawesomeboophis** [comment]
It says the invite is invalid and it won't let me in

**Comment by Firestorm01X2** [comment]
Permanent link to server: https://discord.gg/XW7XhXuZ89
It should work

**Comment by Theawesomeboophis** [comment]
It is asking me to verify via phone number. I don't have a phone number.

**Comment by chaosvolt** [comment]
That sounds like discord's fucked something up, damn. :/

**Comment by Firestorm01X2** [comment]
> It is asking me to verify via phone number. I don't have a phone number.

It was not neccesary for me. I didnt set it.
For now try to solve issues wwith discord

**Comment by chaosvolt** [comment]
I'm fairly certain it's mainly a thing affecting newer users.

**Comment by Firestorm01X2** [comment]
Do not rush - we have all time in the world.

**Comment by Theawesomeboophis** [comment]
It says something out of the ordinary is going on.

**Comment by Firestorm01X2** [comment]
I am AFK for now. Try fix your discord issues. Also you are already on BN server. So just deal with discord- and everything will be fine.
![screenshot 2021-09-06 003](https://user-images.githubusercontent.com/17512620/132259146-907963c8-175a-484f-b0be-5792a669685e.png)

**Comment by Theawesomeboophis** [comment]
I also joined the reddit yesterday, these things are very new to me, I don't use any social media aside from youtube.

**Comment by Firestorm01X2** [comment]
> I also joined the reddit yesterday, these things are very new to me, I don't use any social media aside from youtube.

Technically it is just more different types of forums and chats rather than social media.

**Comment by Theawesomeboophis** [comment]
Yeah, they're border cases, not quite social media or forum either, I will stay away from actual social media however, there's never good news and most of it is drama/conspiracies.

**Comment by Theawesomeboophis** [comment]
I have gotten it to work.

**Comment by Theawesomeboophis** [comment]
My name is the same on discord.

**Comment by Firestorm01X2** [comment]
> 
> 
> My name is the same on discord.

Welome!

**Comment by Theawesomeboophis** [comment]
Oops, sorry, accidentally edited your comment, meant to make my own.

**Comment by Theawesomeboophis** [comment]
How do I set up compose.py and properly use unpacked?

**Comment by Firestorm01X2** [comment]
> 
> 
> How do I set up compose.py and properly use unpacked?

1) https://www.python.org/downloads/ . Use latest version. Make sure to check "Add Python to PATH"
2)  Install Libvips. Download it here: https://github.com/libvips/build-win64-mxe/releases . Grab vips-dev-w64-all-8.11.3.zip.
Extract it to some directory (For example C:\vips) and add C:\vips\bin to windows PATH.
Instruction on how to add things to path look here: https://www.architectryan.com/2018/03/17/add-to-the-path-on-windows-10/
3) Install pyvips. To do it just  write in your console: 
pip install pyvips

And you are done.
After that run \UndeadPeopleUnpacked\!COMPOSE_MAIN.bat to see if it is packing tileset. You will find packed files in UndeadPeopleUnpacked\!dda\ if everything was set right.

**Comment by Theawesomeboophis** [comment]
Downloading and setting up now. ( PS: sorry for slow updates, still working on my spriting skills, but I will update in my spare time in-between real life and gaming ( I still play cataclysm and other games). Hope you understand.

**Comment by Theawesomeboophis** [comment]
Does the guide for the windows path thing work for 8.1 as well?

**Comment by Firestorm01X2** [comment]
> Does the guide for the windows path thing work for 8.1 as well?

Maybe UI will slightly diferent but PATH can be set even on windows 8.1.

>Also. does everybody who wants to contribute have to set this up as well?

It only neccesary to create packed version from unpacked. So it is not strictly neccesary, but contirbutor may want to do it. For example to test his changes ingame.

**Comment by Firestorm01X2** [comment]
> Does the guide for the windows path thing work for 8.1 as well?

https://www.computerhope.com/issues/ch000549.htm#windows8

**Comment by Theawesomeboophis** [comment]
How do I set up cmd prompt so it compiles tileset and do I have to add new sprites and files to unpacked?

**Comment by Firestorm01X2** [comment]
> How do I set up cmd prompt so it compiles tileset

Actually there is no special procedure. Just open command prompt: https://www.businessinsider.com/how-to-open-command-prompt and nivagate to unpacked tileset directory using cd command.
https://www.makeuseof.com/tag/a-beginners-guide-to-the-windows-command-line/

>do I have to add new sprites and files to unpacked?
Yes you should. Looks exisitng tiles as example.
Actually the onlything you should edit is Unpacked version. Packed version - is "compiled result"

**Comment by Theawesomeboophis** [comment]
Thanks, I'll set it up next weekend and have the update ready then.
