### ISSUE TITLE
New name?

### ISSUE THREAD

**Issue by I-am-Erk** [Theawesomeboophis/UndeadPeopleTileset#4]
Every other time this set has changed hands, it's also changed names. It might lead to less confusion if you followed tradition, and would help clarify the new maintainer thing.

For example, you might consider "awesomepeople" or "mx-awesome"

**Comment by Theawesomeboophis** [comment]
This isn't entirely off the table but I'm keeping the name the same for now so the repo is easy to find and use for players who used previous versions.

**Comment by SomeDeadGuy** [comment]
When you start to change sprites I made it will be a good time to change the name.

**Comment by Theawesomeboophis** [comment]
I agree, I do not take credit for your work and don't plan to do so, in the far future I may change the name but I do not plan on it anytime soon.

**Comment by chaosvolt** [comment]
We could also rename it to something specific to the history of the tileset. While I do recall it was put together and did undergo a complete name change once MShock became its author, for a while it managed to avoid a complete name override, becoming MShock Modded back when I was maintaining it, then MShock+ Xotto under Xotto.

Though as MS-Xotto has been revived as a separate tileset now, moving on from that might be warranted for clarity.

**Comment by leemuar** [comment]
Just to support your decision - I found this repository by googling "UndeadPeopleTileset". It would be harder for me to find it with another name probably.

> This isn't entirely off the table but I'm keeping the name the same for now so the repo is easy to find and use for players who used previous versions.
