### ISSUE TITLE
Flesh raptor sprite does not resemble the description.

### ISSUE THREAD

**Issue by I-am-Erk** [Theawesomeboophis/UndeadPeopleTileset#5]
This came up a while back, flesh raptors aren't weird black wyvern things. They're three winged things made from human hands.

The topic of how to draw this came up in discord today, if this helps 

![Screenshot_20210913-164412](https://user-images.githubusercontent.com/45136638/133171180-734de614-9561-42fe-bbaa-b9a1a6e78479.png)

**Comment by Theawesomeboophis** [comment]
Thanks for bringing this up, this is actually in the plans for a resprite after exodii quadrupeds are fixed to match their description. I think raptors will look really cool in the way they're described and it will be great spriting practice.

**Comment by Theawesomeboophis** [comment]
This is coming next update.
