### ISSUE TITLE
NPC holding electric lantern appears to be a talking electric lantern

### ISSUE THREAD

**Issue by LyleSY** [Theawesomeboophis/UndeadPeopleTileset#50]
I'm guessing we just need a small electric lantern version so it looks like someone is holding the lantern

<img width="966" alt="Screen Shot 2022-08-06 at 11 38 06 AM" src="https://user-images.githubusercontent.com/26608431/183255917-a88ac58d-35f5-46e8-9dd2-00f87a8a33f6.png">

**Comment by Theawesomeboophis** [comment]
Yeah, it doesn't have a proper wielded sprite yet.

**Comment by Compu18AI** [comment]
nah, i think you're just talking to a lantern.
