### ISSUE TITLE
Makeshift Blindfold doesn't cover your eyes

### ISSUE THREAD

**Issue by EternalKitten** [Theawesomeboophis/UndeadPeopleTileset#52]
![udp-blindfold](https://user-images.githubusercontent.com/82908191/187711640-6f294001-fb8d-4f82-b93f-633f3f6621f1.png)

When I put on my makeshift blindfold it covers my mouth instead of my eyes.

**Comment by LyleSY** [comment]
Researching this a bit, I don't see makeshift_blindfold defined, so it's failing to this line in the JSON:
`  "looks_like": "scarf",`
So yeah, it looks like a scarf. The fix will be to either change the original JSON to 
`  "looks_like": "blindfold",`
(that is defined in UDP so should fail over nicely) or to create new makeshift_blindfold sprites

**Comment by LyleSY** [comment]
I've submitted a new sprite in the Discord, should fix when it gets merged

**Comment by EternalKitten** [comment]
Thanks a lot mate.

**Comment by LyleSY** [comment]
I believe this was closed by https://github.com/CleverRaven/Cataclysm-DDA/pull/61182

**Comment by EternalKitten** [comment]
Thanks for the fix [LyleSY](https://github.com/LyleSY)! I will close it now!
