### ISSUE TITLE
Can't play in a world with DinoMod on

### ISSUE THREAD

**Issue by Xayrlen** [Theawesomeboophis/UndeadPeopleTileset#53]
**DESCRIPTION**

Whenever I tried to make a character on a freshly made world, I receive a mod_tileset error. Fresh installation of the game and tileset did not resolve the problem. During the process of loading it stops at "Tileset" then gives an error.

**Steps to reproduce**
1. In the graphics settings pick UNDEAD_PEOPLE (NEW VERSION) tileset;
2. Create a new world, with DinoMod on;
3. Create a new character in this world.

**Expected behavior**
After creating a new world with new character, you should be at the character creation section.

**Screenshots**
![1](https://user-images.githubusercontent.com/86978521/190877188-74f9f91c-b43e-4f24-b55d-2f782153f739.png)
![2](https://user-images.githubusercontent.com/86978521/190877189-88e922ad-4bc6-4b0e-a736-fb0fcae78f1d.png)
![3](https://user-images.githubusercontent.com/86978521/190877190-017bda45-0417-4621-b84d-54e8838a745e.png)

**Versions and configuration**
OS: Windows
OS Version: 10
Game Version: 5c4876d [64-bit]
Graphics Version: Tiles
Game Language: English
Mods loaded: 
Dark Days Ahead [dda],
Disable NPC Needs [no_npc_food],
No Fungal Growth [no_fungal_growth],
Bionic Professions [package_bionic_professions],
DinoMod [DinoMod]

**Comment by Theawesomeboophis** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/pull/61089, it was base game issue and should be fixed

**Comment by Theawesomeboophis** [comment]
Can you test just to make sure, need confirmation to close.

**Comment by Xayrlen** [comment]
Can safely confirm that the problem was resolved, sorry for a delay.

**Comment by Theawesomeboophis** [comment]
Thank you, it was a problem with the tileset loading code, I'm glad it's fixed.
