### ISSUE TITLE
Slowdown Issues

### ISSUE THREAD

**Issue by ashGlaw** [Theawesomeboophis/UndeadPeopleTileset#55]
Whenever I'm loading a game and it gets to the tileset portion of the load it hangs, often for minutes at a time, before moving on like nothing's even happened. When I play with a different tileset there's no slowdown. I'm using the latest version of the tileset and a recent experimental build. ( slowdown also occurring when exiting buildings, two issues put into one issue due to the similarities of issues, see https://github.com/Theawesomeboophis/UndeadPeopleTileset/issues/56 for more info).

**Comment by LyleSY** [comment]
Hello, I'd like to pinpoint which PR is causing this. Can you tell me the exact experimental build you're using so I can test?

**Comment by LyleSY** [comment]
And are you using BN or DDA?

**Comment by Theawesomeboophis** [comment]
Tested on latest version on mobile and can not reproduce, can you send pc specs and bn or dda version if it's still occurring, also, is tileset latest version?
