### ISSUE TITLE
Magiclysm tiles not working/displaying.

### ISSUE THREAD

**Issue by octanari** [Theawesomeboophis/UndeadPeopleTileset#57]
I recently started playing again and when I used the latest UDP the monsters for magiclsym were lacking tiles and were only letters, in older versions I know for sure magiclsym has working tiles in UDP. I didn't get an error message of any kind or anything like that and its mostly just the magiclsym related monsters, but a couple of fish had this issue as well.

**Comment by octanari** [comment]
Okay, It fixed itself, Literally, I made no changes to the files and I don't use a launcher, yet I booted it up today and now the tiles are working again. While I'm happy its working again I have no idea what has caused it.

**Comment by Theawesomeboophis** [comment]
Sometimes tiles don't load properly, there's a button in the menu called reload tileset that should fix these sorts of issues without restarting the game.
