### ISSUE TITLE
Missing shocker zombie sprite

### ISSUE THREAD

**Issue by Cyan4235** [Theawesomeboophis/UndeadPeopleTileset#58]
Had a situation where the Shocker Zombie sprite was missing, unfortunately unable to provide a screenshot as I had lost track of the one I found.  Shocker zombie shows no sprite and is therefore invisible.

**Comment by Cyan4235** [comment]
> Had a situation where the Shocker Zombie sprite was missing, unfortunately unable to provide a screenshot as I had lost track of the one I found. Shocker zombie shows no sprite and is therefore invisible.

Also to narrow it down, this is with the Undead People (New Version) tileset, Legacy tileset works as normal.

**Comment by Theawesomeboophis** [comment]
Can you provide a mod list, as this exact error happened before and was due to overlap between mod tileset and base tileset.

**Comment by Cyan4235** [comment]
Here's the list of mods
![image](https://user-images.githubusercontent.com/11711206/197896072-3e705cec-dfe7-4c62-83c4-9d0e0f109973.png)

**Comment by Theawesomeboophis** [comment]
Did you try using the reload tileset button? If you have and it hasn't worked, can you turn off each mod individually until shockers are visible, if they remain invisible, that narrows it down to a dupe sprite in main tileset.

**Comment by Theawesomeboophis** [comment]
Did the methods described work or does the issue persist?

**Comment by LyleSY** [comment]
Crazy cataclysm would be my guess, that has special shockers

**Comment by Theawesomeboophis** [comment]
Crazy Cataclysm was fixed a while ago and there shouldn't be overlap between vanilla and the mod, more info is needed in this case.
