### ISSUE TITLE
This is the newest thing for this tileset? not a backup or anything?

### ISSUE THREAD

**Issue by TheFrozenPancake** [Theawesomeboophis/UndeadPeopleTileset#6]
Just a simple yes or no will do. im just a bit confuzzled on what happened since this seems to change hands every now and then...and does it work with the newest version?

**Comment by TheFrozenPancake** [comment]
and do i need to do anything when i unpack it into the folder with the other tilesets...like delete anything or something

**Comment by Theawesomeboophis** [comment]
Yes, I plan on maintaining this and it should work on latest experimental, if it doesn't, please report it in a issue.
