### ISSUE TITLE
Tileset version roll back

### ISSUE THREAD

**Issue by Xayrlen** [Theawesomeboophis/UndeadPeopleTileset#68]
**Describe the bug**

A few days ago the map tileset suddenly changed as if it got rolled back to the old version, althoguht I have the latest one installed. Now a lot of stuff is simply missing or became symbols. Tileset used is undead_people (new version).
![123](https://user-images.githubusercontent.com/86978521/216631539-e0bd24e2-f814-4b18-ba20-82246238d11a.png)
![12345](https://user-images.githubusercontent.com/86978521/216631557-eb1b9726-e9cf-4893-a475-f973cb900db5.png)
![123456](https://user-images.githubusercontent.com/86978521/216631570-3c50da4f-081b-4d8f-8769-fc9b6792a4f4.png)

**Steps to reproduce**

- Change overmap tileset to *UNDEAD_PEOPLE (NEW VERSION)* in the game settings;
- Load up any character on any world'
- Open map.

**Expected behavior**

You can easily see that from the trees and housing that were like that way before. What's weird, is that the the relevant tiles are still in the folder, like this one.
![1234](https://user-images.githubusercontent.com/86978521/216631866-a195f7f3-7cb5-4704-bb8a-d00a0664a18d.png)

**Versions and configuration**

OS: Windows 10 Pro, 22H2, 19045.2486;
Game Version: a0d3567 [64-bit];
Graphics Version: Tiles;
Game Language: English;
Mods loaded:
![123](https://user-images.githubusercontent.com/86978521/216633975-f18b9566-8997-4b03-b510-e72bdbe71434.png)

**Comment by Theawesomeboophis** [comment]
This bug is known, fix is just waiting for merge.
