### ISSUE TITLE
Two-Way Ladders are bugged

### ISSUE THREAD

**Issue by Kantonine** [Theawesomeboophis/UndeadPeopleTileset#73]
Radio Tower Ladders have some misalignment
![image](https://user-images.githubusercontent.com/91917075/218314168-6c5c58f7-a122-4a30-ba45-bf63c92c9112.png)

**Comment by LyleSY** [comment]
This issue is confirmed. Should be a simple fix of moving where the sprite lives on the  tile and posting the fix to unpacked

**Comment by Theawesomeboophis** [comment]
Fixed in unpacked, just waiting for - pack.
