### ISSUE TITLE
Update Character Sprites with Eye Colors

### ISSUE THREAD

**Issue by Abexis** [Theawesomeboophis/UndeadPeopleTileset#8]
Hello! 
Thanks for picking up the maintenance of this tileset. Personally, I think its the best CDDA tileset out there.

Could you update this tileset with the eye colors that have been added to mainline? 

You can use Zets hair mod as a reference if needed.
https://github.com/Zetsukaze/Zets-Hair-Extensions

Cheers!

**Comment by Theawesomeboophis** [comment]
Which eye color update are you referring to, can you provide a link to the PR?

**Comment by Abexis** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/pull/48726

**Comment by Theawesomeboophis** [comment]
Thanks.

**Comment by Theawesomeboophis** [comment]
Yes, that is in my future plans, but my main focus is getting vanilla and in-repo mods up to date first, then I'll begin work on any new items from Kenan Modpack, if you want a particular sprite added, open a issue here, as keeping track of all the new content is rather difficult, and I may miss some things.

**Comment by LyleSY** [comment]
This is almost done in Unpacked now, just needs hazel to be created
