### ISSUE TITLE
tileset does not work with new 3D vision of lower levels with distance fog PR

### ISSUE THREAD

**Issue by hexoby** [Theawesomeboophis/UndeadPeopleTileset#81]
![Capture](https://github.com/Theawesomeboophis/UndeadPeopleTileset/assets/115601667/5adea6fa-c989-4558-8e45-627fe5ea0528)
this tileset does not work with the new 3D vision of lower levels with distance fog pr
instead of showing lower levels it is just black
https://github.com/CleverRaven/Cataclysm-DDA/pull/65738

**Comment by Theawesomeboophis** [comment]
This is being looked into and a fix will hopefully be out soon.

**Comment by exovisor** [comment]
According to my research, it is enough to remove "t_open_air", "t_open_air_rooved", "t_open_air_rooved_outside" from tile_config.json to fix this. You can edit the file yourself until the fix is released.

**Comment by Theawesomeboophis** [comment]
Exovisor, can you send screenshot with changes.

**Comment by Robin644** [comment]
> According to my research, it is enough to remove "t_open_air", "t_open_air_rooved", "t_open_air_rooved_outside" from tile_config.json to fix this. You can edit the file yourself until the fix is released.

@Theawesomeboophis  It seems useful but kind of strange?:
![屏幕截图 2023-06-14 231028](https://github.com/Theawesomeboophis/UndeadPeopleTileset/assets/54061074/04aebc41-6895-46ad-9d20-efd75ee75d03)

**Comment by Theawesomeboophis** [comment]
Strange how? Does it behave weird or something?

**Comment by Robin644** [comment]
> Strange how? Does it behave weird or something?

Perhaps the layered color recognition is not high enough？Don't worry, I just casually mentioned it. The actual effect is still very good:>

**Comment by zakhad** [comment]
> Exovisor, can you send screenshot with changes. Thinking about making your fix official but wanna see how it looks first.

![image](https://github.com/Theawesomeboophis/UndeadPeopleTileset/assets/5264667/edb9d0fd-d904-426b-9fb3-424a723d5616)

I'm currently playing with the adjusted changes, now sure if it messed some things up though, had some weird cutoff from cows and the status effects are also slightly cut off i haven't played in like a couple of weeks though, not sure if it was because of the suggested changes or entirely unrelated.

**Comment by Theawesomeboophis** [comment]
> > Exovisor, can you send screenshot with changes. Thinking about making your fix official but wanna see how it looks first.
> 
> ![image](https://user-images.githubusercontent.com/5264667/246554782-edb9d0fd-d904-426b-9fb3-424a723d5616.png)
> 
> I'm currently playing with the adjusted changes, not sure if it messed some things up though, had some weird cutoff from cows and the status effects are also slightly cut off i haven't played in like a couple of weeks though, not sure if it was because of the suggested changes or entirely unrelated.

Is this happening in current packed as well?
