### ISSUE TITLE
White hair, different

### ISSUE THREAD

**Issue by 0-0-9** [Theawesomeboophis/UndeadPeopleTileset#85]
MSX++UnDeadPeopleEdition
![Screenshot_2023-10-31](https://github.com/Theawesomeboophis/UndeadPeopleTileset/assets/146689537/eaa407de-979a-4ba2-b6a2-40f3f7998a7a)

**Comment by Theawesomeboophis** [comment]
Hmm, that is weird that it doesn't match the other colors.

**Comment by LyleSY** [comment]
Yep, it's copied from two different mods and I didn't feel like recreating white when we already had it. Is this a problem?

**Comment by LyleSY** [comment]
Another option would be to create two variants of each color using the two models we have. I'm not sure how that would look, but maybe great?

**Comment by Theawesomeboophis** [comment]
We could resprite one of the existing hairs to be white instead of remaking the sprite as well.

**Comment by Theawesomeboophis** [comment]
We could resprite one of the existing hairs to be white instead of remaking the sprite as well.
