### ISSUE TITLE
All hairs are disappeared!

### ISSUE THREAD

**Issue by Robin644** [Theawesomeboophis/UndeadPeopleTileset#86]
Version: 2023-12-14-2141,Win10
funny bug,Lol
![image](https://github.com/Theawesomeboophis/UndeadPeopleTileset/assets/54061074/ffd69a67-0f1b-4a37-a3e8-5010a2aeea51)

**Comment by Theawesomeboophis** [comment]
This is known and will be fixed next update.

**Comment by sasichkamega** [comment]
Heisenbergclysm!

**Comment by Robin644** [comment]
> Heisenbergclysm!

LMAO

**Comment by LyleSY** [comment]
Just waiting on a few bugged tiles in unpacked to release the work from https://github.com/Theawesomeboophis/UndeadPeopleUnpacked/pull/101

**Comment by Theawesomeboophis** [comment]
Fixed

**Comment by sasichkamega** [comment]
> Fixed

Good job!
