### ISSUE TITLE
Is it still work?

### ISSUE THREAD

**Issue by IoIqq** [Theawesomeboophis/UndeadPeopleTileset#98]
I want to contribute to our community and this texture pack. How should I start? Also, what are the main things that still need textures?

**Comment by IoIqq** [comment]
I found an ai tools，it may can help the tileset updata

**Comment by Theawesomeboophis** [comment]
No AI, the discord is the place to submit sprites, an update should be out soonish, I'm just on a break atm for personal stuff.

**Comment by IoIqq** [comment]
> No AI, the discord is the place to submit sprites, an update should be out soonish, I'm just on a break atm for personal stuff.

no，I mean the ai can help us to build this,it may make the work more easy,I had try"shrunk"whith ai,it looks good,you can have a look.

**Comment by IoIqq** [comment]
> No AI, the discord is the place to submit sprites, an update should be out soonish, I'm just on a break atm for personal stuff.

![Uploading Image_1716990547235.png…]()

**Comment by IoIqq** [comment]
![Image_1716990547235](https://github.com/Theawesomeboophis/UndeadPeopleTileset/assets/123221699/709c20db-c129-49d7-b8be-1242083330b6)

**Comment by Theawesomeboophis** [comment]
The art does not fit the style we're going for, we decided a while ago not to use AI but we are working on other ways to automate things.

**Comment by IoIqq** [comment]
> The art does not fit the style we're going for, we decided a while ago not to use AI but we are working on other ways to automate things.

The artistic style can be modified through training and altering prompts, and the development speed of AI surpasses everyone's imagination. Why not give it a try?That painting is 100% generated by AI.

**Comment by Theawesomeboophis** [comment]
I do not want to use AI, thank you for the suggestion.

**Comment by IoIqq** [comment]
> I do not want to use AI, thank you for the suggestion.

Alright, I understand. Are you adequately staffed at the moment?

**Comment by Theawesomeboophis** [comment]
Yes, the team is just on break atm for irl reasons. The contributions are a pretty steady flow atm tho and the next update should be a pretty sizeable one.

**Comment by Theawesomeboophis** [comment]
Of course, more contributions are always welcome or even if you don't wanna contribute, bug reporting and tile request are a huge help as well.

**Comment by IoIqq** [comment]
> Yes, the team is just on break atm for irl reasons. The contributions are a pretty steady flow atm tho and the next update should be a pretty sizeable one.

wow that cool，Thank you for your efforts.

**Comment by IoIqq** [comment]
> Of course, more contributions are always welcome or even if you don't wanna contribute, bug reporting and tile request are a huge help as well. 

In my region, many people are enthusiastic about this project and want to contribute to it, but many lack the time and ability to learn pixel art. Can I first introduce them to try AI-generated pixel art? This might be a helpful solution for your project.

**Comment by Theawesomeboophis** [comment]
Thank you for playing, have a nice day, and feel free to stop by the discord linked in the readme if you have any issues or anything.

**Comment by Theawesomeboophis** [comment]
> > Of course, more contributions are always welcome or even if you don't wanna contribute, bug reporting and tile request are a huge help as well. 
> 
> In my region, many people are enthusiastic about this project and want to contribute to it, but many lack the time and ability to learn pixel art. Can I first introduce them to try AI-generated pixel art? This might be a helpful solution for your project.

Truth be told, I'm not good at pixel art either, I recommend to start off with simple things like knives or something to train yourselves. Also, like I said, spriting is not the only way to help or contribute. Bug reports help a lot and reporting missing tiles as well.

**Comment by IoIqq** [comment]
> > > Of course, more contributions are always welcome or even if you don't wanna contribute, bug reporting and tile request are a huge help as well. 
> > 
> > In my region, many people are enthusiastic about this project and want to contribute to it, but many lack the time and ability to learn pixel art. Can I first introduce them to try AI-generated pixel art? This might be a helpful solution for your project.
> 
> Truth be told, I'm not good at pixel art either, I recommend to start off with simple things like knives or something to train yourselves. Also, like I said, spriting is not the only way to help or contribute. Bug reports help a lot and reporting missing tiles as well.

bor，I want to make some contributions, how should I get started? Do I just submit the finished images directly? I'm not quite sure how to write the corresponding code.

**Comment by Theawesomeboophis** [comment]
Yes, you can submit the images on the discord and I or someone on the main team will do the coding.

**Comment by IoIqq** [comment]
> Yes, you can submit the images on the discord and I or someone on the main team will do the coding.

thank you so much

**Comment by IoIqq** [comment]
> Yes, you can submit the images on the discord and I or someone on the main team will do the coding.

could you have a look to discord?I don't know how to beginning

**Comment by Theawesomeboophis** [comment]
You submit the sprites in the tile-submission channel with ids (which can be found in files or on Hitchhikers Guide to the Cataclysm), there are examples in the channel.

**Comment by IoIqq** [comment]
> You submit the sprites in the tile-submission channel with ids (which can be found in files or on Hitchhikers Guide to the Cataclysm), there are examples in the channel.

How can I know which IDs do not have textures?

**Comment by Theawesomeboophis** [comment]
Mostly by playing and testing stuff in-game.  There isn't really a list.
